# Done to increase the memory available to gradle.
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.configureondemand=false
org.gradle.jvmargs=-Xmx4G -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

org.gradle.console.encoding=UTF-8

# Optional: isolate Loom cache to the project
loom.platform.cacheDir=.gradle/loom-cache

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.1
kotlin_version=1.12.3+kotlin.2.0.21
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_version=0.2.2
cobblemon_version=1.8.1
maven_group=com.sergioaguiar.mirageessentials
archives_base_name=mirageessentials

# Dependencies
fabric_version=0.114.0+1.21.1
luckperms_api_version=5.4
night_config_version=3.6.7
gooeylibs_version=3.1.0-1.21.1
placeholder_api_version=2.4.2+1.21
neodaycare_version=1.5.2
adventure_minimessage_version=4.17.0
adventure_fabric_version=5.14.2
